### ISSUE TITLE
Add route perso api

### ISSUE THREAD

**Issue by VPKevin** [quentingrchr/walk-of-art-back#10]

**Comment by VPKevin** [comment]
Ajouter des routes pour ses data perso
Exemple : http://localhost/api/exhibitions**/me**

**Comment by Nephyrr** [comment]
Liste des routes : 
exhibitions
/api/expositions/ ( expo + resa )
/api/exposition/(id)/ 
reservation 
/api/reservations/ ( resa + expo + work + work file )
/api/reservation/ ( resa + expo ) 
Work & WorkFile
/api/works/ ( works + files )
/api/work/ ( work + file )
/api/work-file/ 

To do : 
/api/galleries/
/api/boards/
